version: "3.7"

services:

  api-linter-prod:
    container_name: api-linter-prod
    restart: unless-stopped
    build:
      context: .
    environment:
      - NODE_ENV=production
      - BASIC_AUTH_USER=${BASIC_AUTH_USER}
      - BASIC_AUTH_HASH=${BASIC_AUTH_HASH}
      - SERVER_NAME_LOCAL=${SERVER_NAME_LOCAL}
      - SERVER_NAME_PROD=${SERVER_NAME_PROD}
      - PORT=${PORT}
      - CONTACT_NAME=${CONTACT_NAME}
      - CONTACT_LINK=${CONTACT_LINK}
      - CONTACT_EMAIL=${CONTACT_EMAIL}
      - API_TAG=${API_TAG}
      - API_DESCRIPTION=${API_DESCRIPTION}
      - EXTERNAL_DOCS_NAME=${EXTERNAL_DOCS_NAME}
      - EXTERNAL_DOCS_LINK=${EXTERNAL_DOCS_LINK}
      - API_VERSION=${API_VERSION}
      - API_TITLE=${API_TITLE}
    networks:
      - linting_network_prod
    ports:
      - '${PORT}:${PORT}'

networks:
  linting_network_prod:
    driver: bridge