version: "3.7"

services:

  api-linter:
    container_name: api-linter
    restart: unless-stopped
    build:
      context: .
      target: builder
    volumes:
      - .:/linter
      - /linter/node_modules
    environment:
      - NODE_ENV=development
      - SERVER_NAME_LOCAL=${SERVER_NAME_LOCAL}
      - SERVER_NAME_PROD=${SERVER_NAME_PROD}
      - PORT=${PORT}
      - CONTACT_NAME=${CONTACT_NAME}
      - CONTACT_LINK=${CONTACT_LINK}
      - CONTACT_EMAIL=${CONTACT_EMAIL}
      - API_TAG=${API_TAG}
      - API_DESCRIPTION=${API_DESCRIPTION}
      - EXTERNAL_DOCS_NAME=${EXTERNAL_DOCS_NAME}
      - EXTERNAL_DOCS_LINK=${EXTERNAL_DOCS_LINK}
      - API_VERSION=${API_VERSION}
      - API_TITLE=${API_TITLE}
    command: npm run start:debug
    networks:
      - linting_network
    ports:
      - '${PORT}:${PORT}'
      - '9229:9229'

networks:
  linting_network:
    driver: bridge

volumes:
  npm-cache:
    external: false